namespace: monitoring

bases:
- https://github.com/imixs/imixs-cloud/management/monitoring/imixs-prometheus/base
#- ../base/

resources:
- 050-persistencevolume.yaml
- 060-ingress.yaml

patchesStrategicMerge:
- 010-patch-volumes.yaml


      